---
title: "Topic Modeling of News"
author: "Franziska Löw"
date: "`r format(Sys.Date())`"
output: github_document
---

```{r, include=FALSE}
# load the packages
libs <- c("tidytext","tidyr","readr","lubridate","tm","stm","RColorBrewer","topicmodels",
          "plyr","dplyr","class","knitr","kableExtra","cldr","data.table",
          "htmlTable","ggplot2","gridExtra","jsonlite","stringr","scales","rjson")
lapply(libs, library, character.only = TRUE)
```

## Load Data
```{r}
rm(list = ls())

load("../output/news_cleaned2.Rda")

df$date <- as.Date(df$date)

#col <- brewer.pal(12, name = "Paired")
```

## Reduce Dataframe
```{r}
df %>%
  filter(fb_shares > 0) %>%
  filter(!site %in% c("ndr.de","wdr.de")) %>%
  filter(grepl("bundestagswahl", text_cleaned)) -> btw

btw$ArticleID <- rownames(btw)
```

# Topic Modeling
## Build Corpus
```{r}
btw %>%
  filter(nchar(text_cleaned) > 5) -> btw
```

```{r}
# Build corpus
df.lda <- Corpus(VectorSource(btw$text_cleaned))
# Create document-term matrix
dtm <- DocumentTermMatrix(df.lda)
# Assign name to docs
rownames(dtm) <- make.unique(btw$title)

inspect(dtm)
```

## Run LDA using Gibbs sampling
```{r}
#Set parameters for Gibbs sampling (see https://eight2late.wordpress.com/2015/09/29/a-gentle-introduction-to-topic-modeling-using-r/)
burnin <- 1000
iter <- 1000
keep <- 50

k = 50 # Topics
```

```{r}
t1 <- Sys.time()
lda50 <-LDA(dtm, k, method="Gibbs", control=list(burnin=burnin, iter = iter, keep = keep))
t2 <- Sys.time()
t2 - t1

save(ldaOut, btw, file=paste("../output/models/LDAGibbs",k,".Rda"))
```

```{r}
#write out results (docs to topics)
ldaOut.topics <- as.matrix(topics(ldaOut))
write.csv(ldaOut.topics,file=paste("../output/models/LDAGibbs",k,"DocsToTopics.csv"))
```

```{r}
#top 6 terms in each topic
ldaOut.terms <- as.matrix(terms(ldaOut,6))
write.csv(ldaOut.terms,file=paste("../output/models/LDAGibbs",k,"TopicsToTerms.csv"))
```

```{r}
#probabilities associated with each topic assignment
topicProbabilities <- as.data.frame(ldaOut@gamma)
#rownames(topicProbabilities) <- make.unique(btw$title)

write.csv(topicProbabilities,file=paste("../output/models/LDAGibbs",k,"TopicProbabilities.csv"))
```

```{r}
#Find relative importance of top 2 topics
topic1ToTopic2 <- lapply(1:nrow(dtm),function(x)
sort(topicProbabilities[x,])[k]/sort(topicProbabilities[x,])[k-1])
```

```{r}
#Find relative importance of second and third most important topics
topic2ToTopic3 <- lapply(1:nrow(dtm),function(x)
sort(topicProbabilities[x,])[k-1]/sort(topicProbabilities[x,])[k-2])
```

```{r}
#write to file
write.csv(topic1ToTopic2,file=paste("../output/models/LDAGibbs",k,"Topic1ToTopic2.csv"))
write.csv(topic2ToTopic3,file=paste("../output/models/LDAGibbs",k,"Topic2ToTopic3.csv"))
```

## Explore the model
```{r}
load(file ="../output/models/LDAGibbs 50 .Rda")
```

### Most likely Topics per Article
```{r}
# The topics function from the package is used to extract the most likely topic for each document 
btw.topics <- topics(ldaOut, 3)

# Create Dataframe
doctopics.df <- as.data.frame(t(btw.topics))

doctopics.df %>%
  transmute(ArticleID = rownames(.),
            Topic1 = V1,
            Topic2 = V2,
            Topic3 = V3) -> doctopics.df

doctopics.df$ArticleID <- as.integer(doctopics.df$ArticleID)
doctopics.df[1:10,]

# Add Topic to origian DF
```

### Most likely Words per Topic
```{r}
## Return the top 30 terms.
btw.terms <- as.data.frame(terms(ldaOut, 30), stringAsFactors = FALSE)
btw.terms[1:5,1:10]
```

### Create Topic Labels
```{r}
topicTerms <- btw.terms %>% gather(Topic)
topicTerms <- cbind(topicTerms, Rank = rep(1:30))
topicTerms <- topicTerms %>% filter(Rank < 5)

topicTerms <- topicTerms %>% mutate(Topic = stringr::word(Topic, 2))
topicTerms$Topic <- as.numeric(topicTerms$Topic)

topicLabel <- data.frame()
for (i in 1:50){
  z <- dplyr::filter(topicTerms, Topic==i)
  l <- as.data.frame(paste(z[1,2], z[2,2], z[3,2], z[4,2], sep = " "), stringAsFactors = FALSE)
  topicLabel <- rbind(topicLabel, l)
}
colnames(topicLabel) <- c("Label")

topicLabel
```

### Working with Theta (Topic prevalence)
```{r}
theta <- as.data.frame(posterior(ldaOut)$topics)
head(theta)
```


```{r}
x <- as.data.frame(row.names(theta), stringsAsFactors = FALSE)
#colnames(x) <- c("ArticleID")
#x$ArticleID <- as.numeric(x$ArticleID)

#theta2 <- cbind(x,theta)
```

```{r}
library(corrplot)

c <- cor(theta)
corrplot(c, method = "circle")
```

