---
title: "Topic Modeling of News"
author: "Franziska Löw"
date: "`r format(Sys.Date())`"
output: github_document
---

```{r, include=FALSE}
# load the packages
libs <- c("tidytext","tidyr","readr","lubridate","tm","stm","RColorBrewer",
          "plyr","dplyr","class","knitr","kableExtra","cldr","data.table",
          "htmlTable","ggplot2","gridExtra","jsonlite","stringr","scales","rjson")
lapply(libs, library, character.only = TRUE)
```

## Load Data
```{r, include=FALSE}
#Load Data
rm(list = ls())

load("../output/news_btw.Rda")
load("../output/news_btw2.Rda")
```

```{r}
common_cols <- intersect(colnames(btw1), colnames(btw2))

btw <- rbind(
  btw1[, common_cols], 
  btw2[, common_cols]
)
```

## Remove Articles after 10.10.2017
```{r}
btw %>%
  filter(date < as.Date("2017-10-10")) -> btw
```

## Generate new variables
```{r}
btw$video <- ifelse(grepl("video", btw$title, ignore.case = TRUE), 1,0)
```

## Save data
```{r}
save(btw, file="../output/btw_combined.Rda")
```

```{r}
ggplot(btw, aes(site)) + 
  geom_bar()
```

```{r}
btw %>%
  filter(site == "stern.de") %>%
  arrange(desc(fb_shares)) %>%
  select(title, fb_shares) %>%
  .[1:100,]
```

```{r}
ggplot(btw, aes(date, fill=site)) +
  geom_bar()
```


## Summary Stats
```{r}
df %>%
  group_by(site) %>%
  summarise(obs = n(),
    fb_shares.mean = mean(fb_shares),
            fb_shares.max = max(fb_shares),
            text_length.mean = mean(text_lenght),
            text_length.max = max(text_lenght)) %>%
  htmlTable(align = "l")
```

### Text Length
```{r}
ggplot(btw, aes(x=as.factor(site), y=text_length)) +
  stat_summary(fun.y="median", geom="bar", fill = "blue", alpha = .5) +
  labs(title = "") +
  labs(x="", y="Median Text Length") +
  theme(axis.text.x = element_text(angle = 40, hjust = 1))
```

### Facebook Likes
```{r}
ggplot(btw, aes(x=as.factor(site), y=fb_shares)) +
  stat_summary(fun.y="median", geom="bar", fill = "blue", alpha = .5) +
  labs(title = "") +
  labs(x="", y="Median of Facebook Shares") +
  theme(axis.text.x = element_text(angle = 40, hjust = 1))
```


