---
title: "R Notebook"
output: 
---

```{r}
library(readxl)
library(tidyverse)
```

```{r}
unique_user1 <- read_excel("../data/unique_user1.xls")
unique_user2 <- read_excel("../data/unique_user2.xls")

uu_df <- rbind(unique_user1,unique_user2) %>%
  rename(uniqueUser = `Unique User Tag Mio.`,
         site = Dachmarke,
         date = Tag) %>%
  select(date, site, uniqueUser)
```

```{r}
## Monthly (2003-2017)
unique_user1 <- read_excel("../data/unique_user_2003_2017.xls")
unique_user2 <- read_excel("../data/unique_user_2003_2017_2.xls")

uu_df_full <- rbind(unique_user1,unique_user2) %>%
  mutate(date = as.POSIXct(paste(Jahr,month,"1",sep="-"))) %>%
  rename(uniqueUser = `Unique User Monat Mio.`,
         site = Dachmarke) %>%
  select(date, site, uniqueUser)
```

```{r}
p <- uu_df %>%
  filter(date > as.Date("2017-05-31")) %>%
  ggplot(aes(date, uniqueUser, color=site)) +
  geom_line() +
  geom_vline(aes(xintercept=as.POSIXct("2017-09-24")),
             linetype = 2, color="grey50") +
  scale_color_manual(values = col[c(1,2,3,4,6,7)]) +
  theme(
      #legend.position   = "none",
      legend.text       =  element_text(size=6),
      plot.background   = element_rect("#fafafa", "#fafafa"),
      panel.background  = element_rect("#fafafa"),
      axis.title.x      = element_blank(),
      axis.text.y       = element_text(size = 8)
    ) +
  labs(x="", y="", color="", title = "", 
      caption = "
  Source: AGOF (www.agof.de)
      " )

#ggplotly(p)
ggsave(plot= p,
filename = "../figs/uniqueUser.png", device = "png",
width = 6, height = 4,
        dpi = 600
)
```





